services:

 jupyter:
   image: jupyter/datascience-notebook:latest
   ports:
     - "8888:8888"
   volumes:
     - ".\notebooks:/home/jovyan/work"
   networks:
     - minha-rede

postgres:
   image: postgres:13
   environment:
     POSTGRES_USER: user
     POSTGRES_PASSWORD: senha
     POSTGRES_DB: data_db
   volumes:
     - postgres-data:/var/lib/postgresql/data
   networks:
     - minha-rede
          
volumes:
 postgres-data:

networks:
 minha-rede:

  

